spring:
  application:
    name: liliblog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liliblog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      password: 123456
      port: 6379
      database: 0
      timeout: 5s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 5s


# MyBatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段
      logic-not-delete-value: 0   # 0表示未删除
      logic-delete-value: 1       # 1表示已删除

springdoc:
  api-docs:
    path: /v3/api-docs    # 自定义JSON文档路径
  swagger-ui:
    path: /swagger-ui.html # 自定义UI路径
    enabled: true
knife4j:
  enable: true
  production: false # 生产环境禁用
  setting:
    language: zh-CN