spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liliblog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 2243556144a

# MyBatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml


jwt:
  # 密钥（secret）必须是经过Base64编码的32字节（或更长）的字符串
  secret: "YourBase64EncodedVeryLongSuperSecretKeyForHS256WhichIsAtLeast32Bytes!"
  expiration: 3600000 # 访问令牌有效期，单位毫秒，这里设为了1小时
  refresh-expiration: 604800000 # 刷新令牌有效期，单位毫秒，这里设为了7天